server:
  port: 10086 # 端口
spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中显示
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false   #  不注册自己到eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1